# Generated by Django 3.0.3 on 2020-02-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='person_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Person'),
            preserve_default=False,
        ),
    ]
